services:

  postgres:
    image: postgres:16
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: application
      POSTGRES_PASSWORD: application
      POSTGRES_DB: gotrash
    volumes:
      - ./scripts/dump:/docker-entrypoint-initdb.d:ro
    networks:
      default:
        ipv4_address: 192.168.201.10

networks:
  default:
    name: gotrash_network
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.201.0/26