version: "3.8"
services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: production
    networks:
      - app-network

volumes:
  data: {}

networks:
  app-network:
    driver: bridge
