server:
  port: 8080

spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 5MB
      location: ${FILE_UPLOAD_BASE_DIR}
  application:
    name: gotrash-backend
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect

application:
  security:
    jwt:
      secret-key: ${JWT_SECRET_KEY}
      expiration: ${JWT_EXPIRATION}

cors:
  allowed-origins: ${FRONTEND_ORIGINS}

file:
  upload:
    base:
      dir: ${FILE_UPLOAD_BASE_DIR}
      url: ${FILE_UPLOAD_BASE_URL}

management:
  endpoints:
    web:
      base-path: /
      exposure:
        include: health, info
  endpoint:
    health:
      show-details: always

springdoc:
  api-docs:
    enabled: true
    path: /api/v1/api-docs
  swagger-ui:
    path: /api/v1/api-docs
    config-url: /api/v1/api-docs/swagger-config
    disable-swagger-default-url: true
    url: /api/v1/api-docs
