name: Deploy

on:
  push:
    branches:
      - production

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Copy . file
        run: |
          cp /home/tintin/secret/gotrash/application.properties ./src/main/resources/application.properties

      - name: Run Docker Compose
        run: |
          docker-compose down
          docker-compose up --build -d

      - name: Restart Reverse Proxy
        run: |
          docker restart reverse-proxy
